### ISSUE TITLE
HtmlTreeBuilderState issues

### ISSUE THREAD

**Issue by sucrexyr** [jhy/jsoup#1421] opened 2020-08-07 12:00 UTC
In HtmlTreeBuilderState.java line 934.  When we have a single tag <input>. !startTag.attributes.get("type").equalsIgnoreCase("hidden")
will case the java.lang.NullPointerException.
startTag.attributes will be null

**Comment by FSchumacher** [comment] 2020-08-07 15:33
At JMeter we stumbled over the same problem, where we (wrongly) try to parse Javascript as HTML. Our code expects a `HTMLParsingException` and doesn't cope well with the NPE.

We will probably change our logic to exclude Javascript (and JSON) code from parsing it with jsoup, but it would be nice, if parsing something foul would always throw a proper Exception.

The JMeter bug can be found at https://bz.apache.org/bugzilla/show_bug.cgi?id=64653

**Comment by jhy** [comment] 2020-12-11 05:24
Thanks - this is fixed in 6e3c98c4a578fb7910241e72a5a33014bb8e85f1 and a dupe of #1404

**Closed by jhy** 2020-12-11 05:24 UTC
