### ISSUE TITLE
group and children QueryParser

### ISSUE THREAD

**Issue by gMan1990** [jhy/jsoup#1425] opened 2020-09-16 06:07 UTC
https://github.com/jhy/jsoup/blob/3f0256953a2938875dba33e58004037989985f7d/src/main/java/org/jsoup/select/QueryParser.java#L83

- version: 1.12.1
- error: `body.select(">p>strong,>*>li>strong")` at `,>*>li>strong`
- right: `document.select("body>p>strong,body>*>li>strong")`

**Comment by Ryderxxx** [comment] 2021-05-17 15:29
Hi,

Although the latest released version comes to 1.13.1 now, the problem you mentioned is still there.
I've reimplemented it by code below:
```
String value = "<html><head>h</head><body>" +
                "<li><strong>l1</strong></li>" +
                "<a><li><strong>l2</strong></li></a>" +
                "<p><strong>yes</strong></p>" +
                "</body></html>";

System.out.println(Jsoup.parse(value).body().select(">p>strong,>*>li>strong"));
System.out.println();
System.out.print(Jsoup.parse(value).select("body>p>strong,body>*>li>strong"));
```
The output is as below:
```
Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: String must not be empty
	at org.jsoup.select.QueryParser.parse(QueryParser.java:69)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:54)
	at org.jsoup.select.QueryParser.combinator(QueryParser.java:112)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:92)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:67)
	at org.jsoup.select.Selector.select(Selector.java:106)
	at org.jsoup.nodes.Element.select(Element.java:444)
	at org.jsoup.nodes.Element.select(Element.java:421)
	...
```
And I noticed that this exception is **caused by an empty subQuery** you inputted.
To solve this problem, just change `body.select(">p>strong,>*>li>strong")` to `body.select("p>strong,*>li>strong")`.
Then everything will be fine, it prints:
```
<strong>l1</strong>
<strong>l2</strong>
<strong>yes</strong>

<strong>l2</strong>
<strong>yes</strong>
```

Just a reminder, the results of `body.select("p>strong,*>li>strong")`and `document.select("body>p>strong,body>*>li>strong")` are **not the same**. You can see the output above that `body.select("p>strong,*>li>strong")` includes `<body><li><strong>l1</strong></li></body>` while `document.select("body>p>strong,body>*>li>strong")` does not.

**Comment by Ryderxxx** [comment] 2021-05-17 15:38
To prevent the others from accidentally producing this error, and to improve the robustness of Jsoup. I will submit a **PR** for this issue, which will check whether there's extra ‘>’ in each query statement. If there is, then just ignore instead of end with unnecessary exceptions.

**Comment by Ryderxxx** [comment] 2021-05-17 16:37
I think I've fixed this little bug by changing the code of Jsoup.select.QueryParser

from

```
private String consumeSubQuery() {
        StringBuilder sq = StringUtil.borrowBuilder();
        while (!tq.isEmpty()) {
            if (tq.matches("("))
                sq.append("(").append(tq.chompBalanced('(', ')')).append(")");
            else if (tq.matches("["))
                sq.append("[").append(tq.chompBalanced('[', ']')).append("]");
            else if (tq.matchesAny(combinators))
// ##############################################################
                    break;
// ##############################################################
            else
                sq.append(tq.consume());
        }
        return StringUtil.releaseBuilder(sq);
    }
```

to

```
private String consumeSubQuery() {
        StringBuilder sq = StringUtil.borrowBuilder();
        while (!tq.isEmpty()) {
            if (tq.matches("("))
                sq.append("(").append(tq.chompBalanced('(', ')')).append(")");
            else if (tq.matches("["))
                sq.append("[").append(tq.chompBalanced('[', ']')).append("]");
            else if (tq.matchesAny(combinators))
// ##############################################################
                if (sq.length() > 0)
                    break;
                else
                    tq.consume();
// ##############################################################
            else
                sq.append(tq.consume());
        }
        return StringUtil.releaseBuilder(sq);
    }
```

It has passed the case you mentioned, so there's no need for you to change your code under this situation.

And I'm going to write some more detailed test cases. As soon as I finish, a **PR** will be submitted according to this issue. 

Hope you like it.

**Comment by Ryderxxx** [comment] 2021-05-21 11:55
Here's my [PR](https://github.com/jhy/jsoup/pull/1552).

**Comment by jhy** [comment] 2021-07-15 07:29
Thanks, have merged that improvement

**Closed by jhy** 2021-07-15 07:29 UTC
