### ISSUE TITLE
Jsoup 1.10.2 send wrong request (1.10.1 works fine)

### ISSUE THREAD

**Issue by tetv** [jhy/jsoup#828] opened 2017-02-09 12:14 UTC
The new version 1.10.2 has a bug while processing the url at least in Jsoup.connect().
This means that the url is not decoded properly. The 1.10.1 works fine.
Details:
- "http://www.site.com/?ustate=N,U" (works fine in both platforms)
- "http://www.site.com/?ustate=N%2CU" (works only in 1.10.1)

Therefore, upgrading to 1.10.2 can cause unpredicted results.

Example:
  Jsoup.connect("http://automoviles.autoscout24.es/?ustate=N%2CU")
        .userAgent("Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)").get()
        .select("script[charset]").html()
        .split("\r\n").grep(~/.*totalCount.*/).first()
        .replaceAll(/[^0-9]/, "").toInteger()

**Comment by chinhodado** [comment] 2017-02-12 19:32
I can confirm this. 1.10.2 seems to be having problem connecting to URL with encoded special characters, for example:

> http://yugioh.wikia.com/wiki/%22A%22_Cell_Recombination_Device

**Comment by eos1d3** [comment] 2017-03-04 17:02
Same here:
"news109%2C" will be converted to "news109%252C" for version 1.10.2.
1.10.1 works fine.

**Comment by ThanosFisherman** [comment] 2017-04-12 23:52
Same here. Works fine in 1.9.2 and 1.10.1 versions

**Comment by KevinSmile** [comment] 2017-05-01 07:07
Same here.

**Comment by jhy** [comment] 2017-06-10 20:31
This is fixed by 56a728d which is in 1.10.3. I'll leave this open until that's released. Apologies for the problems this has caused.

**Comment by jhy** [comment] 2017-06-11 19:57
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3

**Closed by jhy** 2017-06-11 19:57 UTC
Labels: fixed
