### ISSUE TITLE
Missing character when extracting 'href'

### ISSUE THREAD

**Issue by shenzj1994** [jhy/jsoup#974] opened 2017-11-15 00:03 UTC
Hi,
I am not quite sure if this is an issue with jsoup or something wrong with my code. But I would appreciate so much if you have time to take a look at this.
**What I want to do:**
Basically I want to make a crawler that fetch the course registration information from my university's website. (https://courses.students.ubc.ca/cs/main?newSession=true).
**What I did:**
1. Extract the link behind the 'Subject Code'.
2. Open the link.
3. Extract the link in the new page. (Behind the 'Course')
4. Continue repeat steps above until reaches a find page that has seating information.
5. Repeat the proves above for all the course links within the website.

**Issue:**
I experienced some weird HTTP 404 errors at very beginning and realized the extracted 'href' value can miss ONE character sometimes. I was doing this with JDK 9 and tried in both Linux and Windows.
For example, the correct link should looks like:
https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=3&dept=xxxx&course=xxx
What I got was something like:
https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjreas&req=3&dept=xxxx&course=xxx
There is a missing 'a' at tname.
The missed character can be completely random. This happens around 10% in the entire job.
I also have the code that can be ran to reproduce this. Please feel free to let me know if you'd like to take a look. Thanks in advance.

**Comment by jhy** [comment] 2017-11-15 00:28
Can you provide a specific HTML snippet (or a test case ideally) that shows this? I can't replicate it:

https://try.jsoup.org/~TPoJh3ZOSxbY3kfEYfkyVnyRTR0

Parses correctly. Seems like there's an issue because the URLs aren't HTML escaped, and some of the arguments look like valid character escapes. But there's fallback code to prevent that authoring error impacting the parse.

**Comment by shenzj1994** [comment] 2017-11-16 22:52
Here is the code for test purpose:

> https://gist.github.com/shenzj1994/036e558c1a1bdb098eff98a4c19df17a

Please run the method 'listAllUrlsInUBC_test()' and it will print out all the desired elements and extractd URLs on that page.
All the URLs should have exactly same length before the 'dept=', and they should all be accessible. In my test, some URLs are ONE character shorter than others and the missing character seems quite random...

**Comment by shenzj1994** [comment] 2017-11-16 23:07
Quick update:
I fall backed to **1.7.1** and this issue disappeared. 
However, after switch back to **1.11.1**, this issue appears again.

**Comment by jhy** [comment] 2017-11-17 00:20
I hit the page and selected those elements on try jsoup: https://try.jsoup.org/~dwa6aYxAr9lC-8tm78MnMfdIH14

Can you point out some instance numbers which have been parsed incorrectly? I can't see any.

Or show an example line from the original HTML and your output parse that is incorrect.

**Comment by shenzj1994** [comment] 2017-11-17 01:41
You are right. The try.jsoup.org has no issue on this. The issue happens when using Jsoup.connect() in the runtime to get webpage. But if I download that page manually using Chrome, and parse it using the local file, everything looks good.
Here is the output of one run by using connect():

> https://gist.github.com/shenzj1994/bb531fedc371f13a8bd4b1f6a67397fc

Some errors but not all:

> Line 2 (262): missing '=' after 'req'
> Line 12 (272): missing 'b' in 'keyname'
> Line 15 (275): missing 'Z' in 'jsessionid'
> Line 20 (280): missing 'U' in 'jsessionid'
> Line 25 (285): missing 'a' of 'pname'.

**Comment by jhy** [comment] 2017-11-17 02:59
OK! Thanks for that. Got it. It's a dupe of #967. 

Sorry that it took me so long to recognize it as such :(

I verified that I can replicate this in 1.11.1 and it is corrected in 1.11.2 (SNAPSHOT)

**Comment by jhy** [comment] 2017-11-17 03:07
If you want to try the fix, I pushed the jar here: http://infohound.net/wip/jsoup-1.11.2-SNAPSHOT.jar

**Closed by jhy** 2017-11-17 03:07 UTC
Labels: bug, duplicate

**Comment by jhy** [comment] 2017-11-17 03:09
try.jsoup uses Jsoup.Connect internally, but if buffers up the HTML so it can display the original as well as the parse tree. So in a way it was working around the bug!
