### ISSUE TITLE
Duplicated attributes getting deleted except "name" attribute

### ISSUE THREAD

**Issue by jpmaida** [jhy/jsoup#2021] opened 2023-10-27 14:53 UTC
Greetings !!!

I was trying Jsoup to build a component and noticed the following behavior:

Using the following snippet

```html
<table class="a" class="b">
	<tr>
		<td>test</td>
	</tr>
</table>
```

with

```java
String filePath = ...
Document document = Jsoup.parse(new File(filePath));
```

results in

```html
<html>
 <head></head>
 <body>
  <table class="a">
   <tbody>
    <tr>
     <td>test</td>
    </tr>
   </tbody>
  </table>
 </body>
</html>
```

As you can notice the "class" attribute gets ripped off. However when I use the following snippet this doesn't happen:

```html
<table>
	<tr>
		<td>
			<input type="text" name="a" name="b" />
		</td>
	</tr>
</table>
```

What is parsed:

```html
<html>
 <head></head>
 <body>
  <table>
   <tbody>
    <tr>
     <td><input type="text" name="a" name="b"></td>
    </tr>
   </tbody>
  </table>
 </body>
</html>
```

Does someone knows why? Is that a bug or was projected to function this way?

**Comment by jhy** [comment] 2023-10-28 05:12
Hi there -- you should update to the current jsoup release, which is 1.16.2. This is a dupe of #1949.

Could you please confirm that updating fixes the issue.

**Closed by jhy** 2023-10-28 05:12 UTC

**Comment by jpmaida** [comment] 2023-10-29 01:59
Thanks for the reply @jhy ... I'have updated as orientated by you but here is the thing, I need the duplicates. I am using jsoup to check whether there is or not duplicated attributes in JSP/HTML pages so JBoss EAP 7 doesn't go in error mode. Is there a way to disable this behavior ?

**Comment by jhy** [comment] 2023-10-29 04:49
There is no setting to retain duplicate attributes. But it is easy to detect their presence, as the parser will emit an error when they are encountered. Here's a sample:

```java
String html = "<p id=1 id=2><input id=3 id=4>";
Parser parser = Parser.htmlParser()
    .setTrackErrors(100)
    .setTrackPosition(true);

Document doc = Jsoup.parse(html, parser);
int dedupeCount = 0;
for (ParseError error : parser.getErrors()) {
    System.out.println(error.getErrorMessage());
    if (error.getErrorMessage().contains("duplicate attribute"))
        dedupeCount++;
}
System.out.println("Elements with duplicate attributes detected=" + dedupeCount);
```

Produces:
```text
Dropped duplicate attribute(s) in tag [p]
Dropped duplicate attribute(s) in tag [input]
Elements with duplicate attributes detected=2
```

Alternatively, you could also simply modify the [`dedupeAttributes()`](https://github.com/jhy/jsoup/blob/2a4a9cf83dea46aff9fc97fc6da808948f5086e0/src/main/java/org/jsoup/parser/HtmlTreeBuilder.java#L447) method in HtmlTreeBuilder.
