### ISSUE TITLE
JSOUP is unencoding '>' in attribute values.

### ISSUE THREAD

**Issue by wardkj** [jhy/jsoup#684] opened 2016-03-01 18:12 UTC
Even when using "Entities.EscapeMode.xhtml", `'&gt;'` is still being converted to '>' when found inside attribute value.

I am using jsoup 1.8.3

**test case:**
```java 
public static void main(String[] args) {
    final Document doc = Jsoup.parse("<input class=\"text\" value=\"&lt;data&gt;\"/>");
    doc.outputSettings().escapeMode(org.jsoup.nodes.Entities.EscapeMode.xhtml);
    System.out.println(doc.select("input.text").get(0));
  }
```
**output is**
`<input class="text" value="&lt;data>">`

Strangely, it doesn't un-encode `'&lt;'` only `'&gt;'` !

**Comment by jhy** [comment] 2016-04-04 03:39
There's not a bug here.

When parsing, any escaped characters are unescaped into the DOM. So the attribute value `&lt;data&gt;` is parsed as `<data>`. If you access `el.attr("value").text()`, you'll correctly get back `<data>`. 

When serializing (i.e. in your example when you're printing out XML/HTML), we escape as few characters as necessary. That is why the `>` is not escaped to `&gt;`; because it's in a quoted attribute, there's no ambiguity that it's closing a tag, so it doesn't get escaped.

However in XML, `<` characters are not allowed in attribute values, so it gets escaped to `&lt;`. (See https://www.w3.org/TR/xml/#NT-AttValue). 

HTML doesn't have that same requirement - only that attribute values end in the same quote character as started (https://html.spec.whatwg.org/multipage/syntax.html#attributes-2), so the `<` is not escaped.

See also https://github.com/jhy/jsoup/issues/528

**Closed by jhy** 2016-04-04 03:39 UTC
Labels: no-repro
