### ISSUE TITLE
add some characters as valid characters that can be used inside css identifier

### ISSUE THREAD

**Issue by mohamad-khorsandi** [jhy/jsoup#1849] opened 2022-10-10 09:47 UTC
in "Selector.select" method if "query" contains a class or id with some special characters method throws exception with message "could not parse query..."
(for example : "div.classNameWithSpecialCharacters1")

this is because this method uses "TokenQueue.consumeCssIdentifier" that considers only [0-9A-Za-z] ,'-' and '_' as valid character to use in css class or id name.
but according to https://www.w3.org/TR/CSS21/syndata.html#characters seem like there are other characters that can be used inside css identifier

"Selector.select" used inside "Element.cssSelector" so it fails in case element(or possibly its parents) has a class or id with special characters

**Comment by jhy** [comment] 2023-01-05 09:15
Yes. This is effectively a dupe of #1442, will close, and we can revise that PR.

**Closed by jhy** 2023-01-05 09:15 UTC
