### ISSUE TITLE
Returns 403 when it should 200

### ISSUE THREAD

**Issue by tjcoder** [jhy/jsoup#1969] opened 2023-06-12 12:16 UTC
```
var url = "https://www.elfcosmetics.com/brow-comb-+-brush/1807.html";
var response = Jsoup.connect(url);
```

This returns the 403 error code.

but this works:

```
var connection = (HttpURLConnection) new URL(url).openConnection();
connection.setRequestMethod("GET");
connection.setRequestProperty("User-Agent", USER_AGENT);

int responseCode = connection.getResponseCode();
if (responseCode == HttpURLConnection.HTTP_OK) {
    var content = new StringBuilder();
    try (var reader = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
        String line;
        while ((line = reader.readLine()) != null) {
            content.append(line);
        }
    }

    document = Jsoup.parse(content.toString());
}

connection.disconnect();
```

Jsoup version is 1.16.1

**Comment by jhy** [comment] 2023-09-08 01:07
This was caused by incorrectly recoding the path, and is fixed in #1952.

**Closed by jhy** 2023-09-08 01:07 UTC
Labels: duplicate, fixed
