### ISSUE TITLE
Attributes with `-`, `.`, or digits are dropped with OutputSettings.Syntax.xml in 1.18.2

### ISSUE THREAD

**Issue by dn-mib** [jhy/jsoup#2235] opened 2024-11-28 09:45 UTC
Hello!
We tried to upgrade our application today to 1.18.2. But many tests fail. Looks like hyphens are not working anymore.

To reproduce: 

``` java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

public class JsoupTest {
    public static void main(String[] args) {
        Document doc = Jsoup.parseBodyFragment("<p>Hello <a href=\"https://example.com/\">world</a>!</p>")
                .outputSettings(new Document.OutputSettings().syntax(Document.OutputSettings.Syntax.xml));
        Element a = doc.selectFirst("a");
        a.attr("target", "_blank");
        a.attr("data-first-test", "1");
        a.dataset().put("second-test", "2");
        System.out.println(doc.body().html());

        // 1.18.1 => <p>Hello <a href="https://example.com/" target="_blank" data-first-test="1" data-second-test="2">world</a>!</p>
        // 1.18.2 => <p>Hello <a href="https://example.com/" target="_blank">world</a>!</p>
    }
}
```

**Comment by jhy** [comment] 2024-11-28 23:16
Hi!

Arg, sorry about that. Looks like the cause is 27e7d5f03d85bea15fbfe5432c37c6de94965a82. I missed including the allowed `-` when converting this regex: `"[a-zA-Z_:][-a-zA-Z0-9_:.]*"`

**Comment by jhy** [comment] 2024-11-28 23:50
Fixed - had also missed digits and `.`. Also improved the coverage, I thought we had included better coverage initially.

Will keep this issue open for visibility until released in 1.18.3.

**Comment by jhy** [comment] 2024-12-01 23:19
(Closing now that [1.18.3](https://github.com/jhy/jsoup/releases/tag/jsoup-1.18.3) is released.)

**Closed by jhy** 2024-12-01 23:19 UTC
Labels: bug, fixed

**Comment by dn-mib** [comment] 2024-12-02 07:09
I can confirm it works in 1.18.3. Thanks for the fix and a great html lib. :)

**Comment by cassiork** [comment] 2025-02-05 15:24
pessoal, primeiramente boa tarde.

eu sendo clonado pelo grupo de voces a mais de 1 ano... preciso de uma ajuda de vcs...estou ddoente ...depressao.... sera que voces conseguem me passa o nome do cliente que solicitou a clonagem do meu celular para voces e pedir com muita humildade para voces parar com a clonagem, em troca eu eu nao faco nenhum tipo de denuncia....ok?

posso  contar com voces?
