### ISSUE TITLE
ns|tag selector finds target, but *|tag selector does not

### ISSUE THREAD

**Issue by slawo-ch** [jhy/jsoup#1308] opened 2020-01-27 18:49 UTC
I'm parsing an XML document with namespaces like this:

```xml
<?xml version="1.0"?>
<soap:Envelope
        xmlns:soap="http://www.w3.org/2003/05/soap-envelope/"
        soap:encodingStyle="http://www.w3.org/2003/05/soap-encoding">
    <soap:Body xmlns:m="http://www.example.org/stock">
      Hello World!
    </soap:Body>
</soap:Envelope>
```

When selecting `soap|Envelope`, I get the expected top level tag.
When selecting `*|Envelope`, I get nothing. 

Quick Junit test case:

```java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.junit.Test;

import static org.junit.Assert.*;

public class SoupTest {

  private static String xmlText = "<?xml version=\"1.0\"?>\n" +
      "<soap:Envelope\n" +
      "        xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope/\"\n" +
      "        soap:encodingStyle=\"http://www.w3.org/2003/05/soap-encoding\">\n" +
      "    <soap:Body xmlns:m=\"http://www.example.org/stock\">\n" +
      "        Hello World!\n"+
      "    </soap:Body>\n" +
      "</soap:Envelope>";

  @Test
  public void finds_envelope_tag_with_specific_ns_prefix_selector() {
    Document parsed = Jsoup.parse(xmlText, "", Parser.xmlParser());
    Elements foundItems = parsed.select("soap|Envelope");
    assertEquals("finds one tag", 1, foundItems.size());
    assertEquals("finds the envelope tag", "soap:Envelope", foundItems.get(0).tagName());
  }

  @Test
  public void finds_envelope_tag_with_wildcard_ns_prefix_selector() {
    Document parsed = Jsoup.parse(xmlText, "", Parser.xmlParser());
    Elements foundItems = parsed.select("*|Envelope");
    assertEquals("finds one tag", 1, foundItems.size());
    assertEquals("finds the envelope tag", "soap:Envelope", foundItems.get(0).tagName());
  }
}
```
The second test fails, as the call to select returns Elements of size 0.

**Comment by jhy** [comment] 2020-01-31 02:04
Thanks. This looks like a dupe of #1268. 

I think the implementation currently is a bit lazy and only works through the HTML parser, not the XML parser. The latter actually does namespaces; the former just puts it all into the tag name, and the selector does some string matching (from memory). So we'll need to update the selector to test namespaces specifically.

**Closed** 2020-01-31 19:13 UTC
Labels: duplicate
