### ISSUE TITLE
Nested selects do not work with "src"

### ISSUE THREAD

**Issue by remisbaima** [jhy/jsoup#580] opened 2015-05-22 13:33 UTC
I am using jsoup v1.8.2. In jsoup 1.8.1 it was working normally.
The nested select does not work in the HTML: https://gist.github.com/remisbaima/70f8cf0c6e3160695791

To reproduce run:
```java
    public static void main(final String[] args) throws Exception {
        final String url = "https://gist.githubusercontent.com/remisbaima/70f8cf0c6e3160695791/raw/54e2ea555e958ef9a8d97c4b1dff119afc957cc0/startpage";
        final Document d = Jsoup.parse(new URL(url), 10000);
        System.out.println(d.select("div#contentgrid_16_2").select("[src=/media/_tech/layout/images/spacer.gif]"));
    }
```
and you will see in the output only 1 occurrence:
```html
<img src="/media/_tech/layout/images/spacer.gif">
```

The correct behavior should be that we see 4 occurrences of the "img" above, as when you run:
```java
System.out.println(d.select("[src=/media/_tech/layout/images/spacer.gif]"));
```
you will see 4 occurrences and they are all inside the "div#contentgrid_16_2":
```html
<img src="/media/_tech/layout/images/spacer.gif">
<img src="/media/_tech/layout/images/spacer.gif">
<img src="/media/_tech/layout/images/spacer.gif">
<img src="/media/_tech/layout/images/spacer.gif">
```

**Comment by jhy** [comment] 2015-07-05 22:25
Thanks. This is a dupe of #554 (fixed).

**Closed by jhy** 2015-07-05 22:25 UTC
