### ISSUE TITLE
CSS selector unable to parse table tags in 1.14.3

### ISSUE THREAD

**Issue by bitbythecron** [jhy/jsoup#1677] opened 2021-11-27 20:33 UTC
Potential bug, when I run:
```
String htmlString = "<html><head><title>My Soup Materials</title><!--mstheme--><link rel=\"stylesheet\" type=\"text/css\" href=\"../../_themes/ice/ice1011.css\"><meta name=\"Microsoft Theme\" content=\"ice 1011, default\"></head><body><center><table width=\"92%\"><tbody><tr><td><h2>My Soup Materials</h2><table width=\"100%%\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td align=\"left\"><b>Origin:</b> Belgium</td><td align=\"left\"><b>Count:</b> 2 foos</td></tr><tr><td align=\"left\"><b>Supplier:</b> </td><td align=\"left\"><b>Must Burninate:</b> Yes</td></tr><tr><td align=\"left\"><b>Type:</b> Fizzbuzz</td><td align=\"left\"><b>Add Afterwards:</b> No</td></tr></tbody></table><br><b><u>Notes</b></u><br>Drink more ovaltine</td></tr></tbody></table></center></body></html>";
Document document = Jsoup.parse(htmlString);
Elements allTables = document.select("table");
Element table = allTables.get(0);
```

The `allTables` instance is empty (size = 0), **why?**  When the runtime executes `allTables.get(0)` I get an `IndexOutOfBoundsException`.

**Comment by damienhunter30** [comment] 2021-12-18 22:42
`import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class Test {
	public static void main(String [] args) {
		String htmlString = "<html><head><title>My Soup Materials</title><link rel=\"stylesheet\" type=\"text/css\" href=\"../../_themes/ice/ice1011.css\"><meta name=\"Microsoft Theme\" content=\"ice 1011, default\"></head><body><center><table width=\"92%\"><tbody><tr><td><h2>My Soup Materials</h2><table width=\"100%%\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td align=\"left\"><b>Origin:</b> Belgium</td><td align=\"left\"><b>Count:</b> 2 foos</td></tr><tr><td align=\"left\"><b>Supplier:</b> </td><td align=\"left\"><b>Must Burninate:</b> Yes</td></tr><tr><td align=\"left\"><b>Type:</b> Fizzbuzz</td><td align=\"left\"><b>Add Afterwards:</b> No</td></tr></tbody></table><br><b><u>Notes</b></u><br>Drink more ovaltine</td></tr></tbody></table></center></body></html>";
		Document document = Jsoup.parse(htmlString);
		Elements allTables = document.select("table");
		
		int x = 0;
		
		for(Element table : allTables){
			System.out.println(allTables.get(x));
			x++;
		}
	}
}`

I tried it and I'm not seeing what the issue is. What version was this bug in?

**Comment by jhy** [comment] 2021-12-19 04:51
Works for me too: https://try.jsoup.org/~8N0WqqBXts0968HPh1YEKQSroUc

**Comment by damienhunter30** [comment] 2021-12-19 11:57
I'm assuming OP, that the issue might be, instead of creating a list of Elements from the input string, you tried to go straight for Element selection. Now, I could be way off, but it's the only reason I can think of.

You said it threw an out of bounds exception, which might happen, if you actually haven't declared an array of collection of elements in the first place.  Again, I could be wrong.

**Comment by jhy** [comment] 2021-12-30 00:34
Closing, please re-open if you have a reproducing code sample.

**Closed by jhy** 2021-12-30 00:34 UTC
Labels: no-repro, needs-more-info
