### ISSUE TITLE
Bug in nextSiblingElement()

### ISSUE THREAD

**Issue by huuson94** [jhy/jsoup#578] opened 2015-05-20 03:56 UTC
If a page has 2 tags, they have same contains. 2nd ones's nextSiblingElement() function will return the first one.
Example

![image](https://cloud.githubusercontent.com/assets/8952023/7718732/d9fc9746-fede-11e4-8a2f-02c70d583977.png)

**Comment by jhy** [comment] 2015-07-06 02:50
Thanks. This is a dupe of #561 (fixed)

**Closed by jhy** 2015-07-06 02:50 UTC
