### ISSUE TITLE
latest build breaks style overides - new style not added to existing defined styles

### ISSUE THREAD

**Issue by footloosejava** [jhy/jsoup#586] opened 2015-06-05 20:05 UTC
Seems random, proved working on previous version.

If an element has a style defined, the style info should be added to the css style. Sometimes it is not.

Reverting back to 1.8.1 solved the problem.

First noticed when my client html emails started looking funny ...

**Comment by jhy** [comment] 2015-07-06 03:36
Thanks. Dupe of #561

**Closed by jhy** 2015-07-06 03:36 UTC
