### ISSUE TITLE
Erroneous parsing of XML content

### ISSUE THREAD

**Issue by wojtuch** [jhy/jsoup#934] opened 2017-08-15 15:31 UTC
Hello,

I've noticed that when processing certain XML content, the parser malfunctions.
That's the snippet of the XML document that I am processing:

`والجدير بالذكر أن الدورات النقابية المتعاقبة منذ عام 1950م وحتى 2011م بلغت خمسة عشر دورة تتفاوت في آجالها من عام لعامين ولأربعة أعوام ثم خمسة أعوام اعتباراً من دورة 1996_2001 م حسب نصوص القوانين وتطوراته
</doc>
<doc id="1432834" url="https://ar.wikipedia.org/wiki?curid=1432834" title="ريتا حايك"> `

However, after parsing the file (either with `doc = Jsoup.parse(File f)` or `doc = Jsoup.parseBodyFragment(String s)`), when printing the element's content (`doc.html()`), I notice that one `doc` closing tag turns to a comment closing:

`والجدير بالذكر أن الدورات النقابية المتعاقبة منذ عام 1950م وحتى 2011م بلغت خمسة عشر دورة تتفاوت في آجالها من عام لعامين ولأربعة أعوام ثم خمسة أعوام اعتباراً من دورة 1996_2001 م حسب نصوص القوانين وتطوراته
</doc-->
<doc id="1432834" url="https://ar.wikipedia.org/wiki?curid=1432834" title="ريتا حايك"> `

Because of that all the remaining content (over 50MB) is loaded as one doc.
Does anything come to your mind? Am I doing something wrong or should this be considered a bug?

**Comment by jhy** [comment] 2017-10-10 04:15
Hi!

Could you put the original file somewhere where I can pick it up and test? I tried to copy&paste but couldn't replicate on try.jsoup.org. I wonder if there's a BOM at the start of the file, or another tag that isn't in your snippet, that is causing the problem.

**Comment by wojtuch** [comment] 2017-10-23 11:38
Hi!

The following file is produced by https://github.com/attardi/wikiextractor applied on the arabic wikipedia dump:
[jsoup-problem.txt](https://github.com/jhy/jsoup/files/1406902/jsoup-problem.txt)

````
$ file jsoup-problem.txt                                                                                                                                                                                                                                  
jsoup-problem.txt: UTF-8 Unicode text, with very long lines
````
I guess there is no BOM, I couldn't find any other unusual tag neither.

**Comment by krystiangorecki** [comment] 2017-11-21 22:49
I managed to separate as few as possible characters to reproduce. Try this one:
```
	String htmlFragment = "<doc id=\"1432821\">ي </1971ن </doc>";
	System.out.println(Jsoup.parseBodyFragment(htmlFragment));
```
But beware, original file behaves strangely when editing. For example using Notepad++ when I add space somewhere some other characters change appearance and some others disappear. I'm not familiar with encodings and characters like these, but in my pasted example after deleting some letters, remaining characters formed "/>".
<kbd>
![1](https://user-images.githubusercontent.com/10375973/33100515-f68a1aa6-cf14-11e7-9151-bf30b30c8027.gif)
</kbd>


Another example:
<kbd>
![2](https://user-images.githubusercontent.com/10375973/33100521-f94f9608-cf14-11e7-831c-170d1e88ac7a.gif)
</kbd>

**Comment by jhy** [comment] 2017-11-24 01:05
@krystiangorecki, if you look at the character array for the string you posted, it actually looks like this:

`<doc id="1432821">s </1971u </doc>`

(Where I have used 's' and 'u' to represent the original characters.)

XML is a LTR character based language. The Arabic letter when rendered (in browser or IDE) is putting the rendered into RTL mode, so the input doesn't render as the actual array is ordered. That's why this output looks like that, and why you're seeing the odd backspace issues.

I'm not sure if that's the same issue as the original (maybe the XML output generator has some issues with RTL), or if that's just a copy&paste issue.

**Comment by krystiangorecki** [comment] 2017-11-25 00:05
That's not copy&paste issue as the same happens when parsing original example file. At some point when parsing doc#1432821 when reader bufPos=11449 state switches from `Data` to `TagOpen` then to `EndTagOpen` and then to `BogusComment`.

**Comment by jhy** [comment] 2021-07-10 08:47
(Closing out as we've had no other related reports which I would expect if there is an endemic issue - expect this was root-caused by a document flipping around the text order.)

**Closed by jhy** 2021-07-10 08:47 UTC
