### ISSUE TITLE
android lint check issue

### ISSUE THREAD

**Issue by lipanpan1030** [jhy/jsoup#1338] opened 2020-03-12 03:51 UTC
when lint check this issue: TrustAllX509TrustManager , 
this class org.jsoup.helper.HttpConnection$Response$2 report lint exception. 
exactly message below:

Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers

I really want this issue be fixed.
thank you very much

**Comment by jhy** [comment] 2021-01-05 08:56
Dupe of #912. Please use a current version.

**Closed by jhy** 2021-01-05 08:56 UTC
