### ISSUE TITLE
java.io.IOException: Mark has been invalidated. jsoup:1.11.2

### ISSUE THREAD

**Issue by criss721** [jhy/jsoup#992] opened 2017-12-13 07:24 UTC
```
12-13 10:47:38.070: W/System.err(29120): java.io.IOException: Mark has been invalidated.
12-13 10:47:38.070: W/System.err(29120): 	at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
12-13 10:47:38.071: W/System.err(29120): 	at org.jsoup.internal.ConstrainableInputStream.reset(ConstrainableInputStream.java:103)
12-13 10:47:38.071: W/System.err(29120): 	at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:105)
12-13 10:47:38.071: W/System.err(29120): 	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:832)
12-13 10:47:38.071: W/System.err(29120): 	at ir.homer.passenger.activity.ActivityCategory$1.run(ActivityCategory.java:66)
12-13 10:47:38.071: W/System.err(29120): 	at java.lang.Thread.run(Thread.java:818)
```
i got this Exception on Android 6 (htc m8)
Jsoup work as well on other device !
**data** is this : https://trello-attachments.s3.amazonaws.com/5a0c89594a6072467d5131db/5a26ff8ab1c70314c170d882/701ddf2d472eea8e7d23fc250800adcb/cat.json

> .maxBodySize(1024 * 1024 * 10) is just added to test for debug

```
          SSLHelper.enableSSLSocket();
          Connection.Response response = Jsoup
            //.connect(Urls.filter_cat_list)
            .connect("https://trello-attachments.s3.amazonaws.com/5a0c89594a6072467d5131db/5a26ff8ab1c70314c170d882/701ddf2d472eea8e7d23fc250800adcb/cat.json")
            .maxBodySize(1024 * 1024 * 10)
            .header("Authorization", authorization)
            .method(Connection.Method.POST)
            .validateTLSCertificates(true)
            .timeout(5000).followRedirects(true)
            .execute();
```

**about SSLHelper**

```
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.X509TrustManager;

/**
 * Created by Javad on 2017-12-05 at 8:29 PM.
 */
public class SSLHelper {

  public static void enableSSLSocket() throws KeyManagementException, NoSuchAlgorithmException {
    HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
      public boolean verify(String hostname, SSLSession session) {
        return true;
      }
    });

    SSLContext context = SSLContext.getInstance("TLS");
    context.init(null, new X509TrustManager[]{new X509TrustManager() {
      public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
      }

      public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
      }

      public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0];
      }
    }}, new SecureRandom());
    HttpsURLConnection.setDefaultSSLSocketFactory(context.getSocketFactory());
  }
}
```

**Comment by criss721** [comment] 2017-12-13 07:53
A downgrade to Jsoup 1.10.3  solved the problem 😁

**Comment by Frasprite** [comment] 2017-12-14 15:07
I had the same problem me too.
I confirm that with Android 7 (Nougat) there is no problem, but with other previous version I get this error.
The downgrade is just a temp fix (until there is a new version which fix the issue), thank you.

**Comment by jhy** [comment] 2017-12-21 23:36
Dupe of #990

**Closed by jhy** 2017-12-21 23:36 UTC
Labels: duplicate
