### ISSUE TITLE
Duplicate children roll up into 1

### ISSUE THREAD

**Issue by RNGuy** [jhy/jsoup#579] opened 2015-05-20 14:38 UTC
Duplicate elements are rolled up into one. This has been confirmed for `<td>` and `<span>`. Below is sample HTML and the result that is printed to console.

Tested on jsoup v1.8.2.

```java
System.out.println(Jsoup.parse("<html><body><table><tr><td> VALUE </td><td> VALUE </td></tr></table></body></html>").select("td:nth-child(1)"));
// <td> VALUE </td>
// <td> VALUE </td>

System.out.println(Jsoup.parse("<html><body><table><tr><td> VALUE </td><td> VALUE </td></tr></table></body></html>").select("td:nth-child(2)"));
// (Prints newline only)

System.out.println(Jsoup.parse("<html><body><table><tr><td> VALUE </td><td> VALUE2 </td></tr></table></body></html>").select("td:nth-child(1)"));
// <td> VALUE </td>

System.out.println(Jsoup.parse("<html><body><table><tr><td> VALUE </td><td> VALUE2 </td></tr></table></body></html>").select("td:nth-child(2)"));
// <td> VALUE2 </td>

System.out.println(Jsoup.parse("<html><body><table><tr><td> VALUE </td><td> VALUE </td></tr></table></body></html>").select("td:last-child"));
// (Prints newline only)
```

**Comment by jhy** [comment] 2015-07-05 22:24
Thanks. This is a dupe of #554 (fixed).

**Closed by jhy** 2015-07-05 22:24 UTC
