### ISSUE TITLE
Processing a larg html table

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [jhy/jsoup#1252] opened 2019-08-30 12:55 UTC
When I try to parse a large html page that has a table with thousands of rows, when I call select("tr") jsoup does not return all existing rows. Jsoup only returns a fraction of all existing rows in a large table with thousands of rows.

```
doc = Jsoup.connect(url).timeout(10 * 1000).get();
Element table = doc.select("table").get(0);
Elements rows = table.select("tr");
for (int i = 1; i <= rows.size() - 1; i++)
{
// rows.size() is less than the original number of nodes in the table.
}
```

**Comment by AmirHossein-SayyadAbdi** [comment] 2019-08-30 12:57
I should also mention that the web page contents are static.

**Comment by krystiangorecki** [comment] 2019-09-01 11:18
It's probably a matter of setting **maxBodySize**.
https://jsoup.org/apidocs/org/jsoup/Connection.html#maxBodySize-int-

> Set the maximum bytes to read from the (uncompressed) connection into the body, before the connection is closed, and the input truncated. The default maximum is 1MB. A max size of zero is treated as an infinite amount (bounded only by your patience and the memory available on your machine).

try 
`doc = Jsoup.connect(url).timeout(10 * 1000).maxBodySize(0).get();`

Btw, it would be more suitable to ask this question on stackoverflow, not here :)

**Comment by AmirHossein-SayyadAbdi** [comment] 2019-09-01 18:46
Thanks, the issue is resolved.
I had no idea there was a limit on maximum body size, so I thought it was a problem and then I created an issue here.
Sorry ;)

**Comment by HansBrende** [comment] 2019-09-02 04:45
@AmirHossein-SayyadAbdi If the issue is resolved, you can close it.

**Closed** 2019-09-02 06:50 UTC

**Comment by jhy** [comment] 2020-01-26 23:27
I upped the default to 2MB to help reduce the incidence rate of this.

86d69ea625edc3650b50b8f13364c58a173fb9bf
