### ISSUE TITLE
Out of memory on Jsoup.connect(UrlPath).get()

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [jhy/jsoup#621] opened 2015-09-02 15:55 UTC
Hi,

I have added _Jsoup 1.8.1_ as a module in my Android application.

I created a sync class that use multiple HTTP connection to syncronize a sqlite database, used from the application. The syncronization is made using a Jsoup connection to a WS RestFull.

The **Out Of Memory Exception** is verified (not always) when I try to get WS result of a table that contains about 60 thousands records.

My connection to WS is something like this:
`Document WS_Document = Jsoup.connect(UrlPath).maxBodySize(0).timeout(10 * 100000).get();`

I used the `.maxBodySize(0)` to manage large XML results and `.timeout(10 * 100000)` to prevent the elaborations of WS that I am calling from application.

But even though I set on my `manifest.xml` the attribute `android:largeHeap="true"`, and the aplication use 256 MB of memory, I get the **Out Of Memory Exception** (Only with very big table).

I try to see what the application do when I launch the sync method. Looking the **Memory Monitor** of **Android Studio** and whatching the log in LogCats, It's clearly visible that when the application start to execute the command:
`Document WS_Document = Jsoup.connect(UrlPath).maxBodySize(0).timeout(10 * 100000).get();`
the instruction start to allocate memory until it exceeds the memory limit of this famous 256 MB.
I've also tried to call the Garbage Collector (`System.gc();`) before and after the instuction to free all memory that I can but nothing change and the application crash with **Out Of Memory Exception** error.

Please help me to solve this problem.

Best Regards

**Comment by jhy** [comment] 2015-09-03 05:26
What is "WS"?

What Android version and what device are you on?

What's the URL, so we can replicate? Can you give a full code snippet and the actual stack trace?

Can you attach a MAT memory dump? That would help understand what's chewing up the memory. Is it the file, what else is going on in the app, etc, are other strings being retained, etc?

What is "very big" in bytes and table rows?

It would be worth trying using 1.8.2, because there's a tweak to memory consumption there (if a node has no attributes, it no longer contains a small empty array list, but just an empty pointer).

Setting maxBodySize(0) would only make memory consumption worse, not better. It limits how much content is read from the URL. Timeout is also not relevant to memory consumption.

At some point, if you can't make enough memory available to parse the content, you may need to partition the content read.

**Comment by MiguelAngelLV** [comment] 2015-09-15 09:34
I thing that "WS" is "WebService"

**Comment by Bruno-Piccinin-RealComm** [comment] 2015-09-15 10:32
Sorry for the delay.

Hi,

> What is "WS"?

WS means Web Service RestFul

> What Android version and what device are you on?

I'm using a Samsung Galaxy Tab 2.0 and it has Android 4.1.2

> What's the URL, so we can replicate? Can you give a full code snippet and the actual stack trace?

The problem is not on URL, neither on result of the Web Service calling. Besides, i cant give you an URL because the WebService is local and not Public.

> Can you attach a MAT memory dump? That would help understand what's chewing up the memory. Is it the file, what else is going on in the app, etc, are other strings being retained, etc?

How can I do that? I trying to use Android Device Monitor but when I try to "dump JAVA Heap" nothing happen.

> What is "very big" in bytes and table rows?

The "very big" in bytes and table rows is the table field's itself. This is an example of a table returned from Web Service
`<addr>`

> It would be worth trying using 1.8.2, because there's a tweak to memory consumption there (if a node has no attributes, it no longer contains a small empty array list, but just an empty pointer).

I can upgrade my library, but I think the really problem is the allocation and creation of the object Jsop Document in case with VERY BIG DATA returned.

> Setting maxBodySize(0) would only make memory consumption worse, not better. It limits how much content is read from the URL. Timeout is also not relevant to memory consumption.

I noted if i remove maxBodySize(0) the Document created by JSOUP is smaller than it should be. For example without maxBodySize(0) i see about 5k nodes instead about 60K I should have.

**Comment by Bruno-Piccinin-RealComm** [comment] 2015-09-30 06:50
This is a example code that show what I mean.
Sample code

`public class MainActivity extends ActionBarActivity {`

    private static Handler mHandler = new Handler();
    private static Context context;
    static TextView textView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        textView = (TextView) findViewById(R.id.textView);


        textView.setText("5 seconds to start task");

        context = this.getApplicationContext();

        mHandler.postDelayed(new Runnable() {
            public void run() {
                new syncDataWS(context).execute();
            }
        }, 5000);

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    private static class syncDataWS extends AsyncTask<Void, String, Void> {

        Context mContext;

        public syncDataWS(Context context) {
            this.mContext = context;
        }

        @Override
        public void onPreExecute() {
            super.onPreExecute();
            textView.append("\nStart task");
        }

        @Override
        protected Void doInBackground(Void... params) {

            try {
                publishProgress("Start call XML page");
                Document WS_Document = Jsoup.connect("URL_XML_EXAMPLE").maxBodySize(0).timeout(10 * 100000).get();
                publishProgress("End call XML page");

                publishProgress("Get rows of document");
                Elements XML_RESULT_WS = WS_Document.select("row");
                publishProgress("Record number : " + Integer.toString(XML_RESULT_WS.size()));

            } catch (IOException e) {
                e.printStackTrace();
            }

            return null;
        }

        @Override
        protected void onProgressUpdate(String... values) {
            super.onProgressUpdate(values);
            if (values != null && values.length > 0) {
                textView.append("\n" + values[0]);
            }
        }

        @Override
        protected void onPostExecute(Void result) {
            textView.append("\nEnd task");
        }
    }
}

And this is a XML EXAMPLE. Put it a host and copy the URL in jsoup.connect

`<XMLDataResponse xmlns="www.example.net"><XMLDataResult><root xmlns=""><row ID="1" ID2="2" ID3="3" ID4="4" F1="0.000000000000000e+000" F2="0.000000000000000e+000" F3="0.000000000000000e+000" F4="" F5="0.000000000000000e+000" F6="0.000000000000000e+000"/></root></XMLDataResult></XMLDataResponse>`

take the tag row and copy + paste in XML EXAMPLE until you have 60 thousand records.

You can watch with your eyes what happend in memory monitor.

I really need a solution, everything can be helpfull.

**Comment by gouessej** [comment] 2015-10-19 09:54
@jhy Did you mean Eclipse MAT? https://www.eclipse.org/mat/

**Comment by jhy** [comment] 2017-06-25 06:56
This is likely the same root cause as #339 and so will be fixed with #904

**Closed by jhy** 2017-06-25 06:56 UTC
