### ISSUE TITLE
.select("[attr^=value]") does not seem to work on this page

### ISSUE THREAD

**Issue by lennycode** [jhy/jsoup#891] opened 2017-05-31 19:15 UTC
view-source:https://www.walmart.com/search/?query=031604016173

There are only 4 instances of the attribute value "ProductTileListView-[0-9]{1}" on the page. Yet it returns 381. I tried different combinations of matching operators, regex only to get the same result each time.

![walmart](https://cloud.githubusercontent.com/assets/845855/26649158/f2de65b4-4612-11e7-8510-a8b8bc2f3536.png)

**Comment by krystiangorecki** [comment] 2017-06-01 22:46
I can't reproduce. It shows always **4**. Tested with 1.10.2, 1.10.1, 1.9.2 and 1.8.1.
```
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

public class JsoupIssue891 {
	public static void main(String[] args) throws MalformedURLException, IOException {
		Document doc = Jsoup.parse(new URL("https://www.walmart.com/search/?query=031604016173"), 10000);
		Elements elements = doc.select("[data-tl-id^=ProductTileListView]");
		System.out.println(elements.size());
	}
}

```

**Comment by lennycode** [comment] 2017-06-02 13:11
Thanks, that works. However, my original code was actually like this:
`Elements elements = doc.select("div")`

I was using the collection of divs for other purposes. I thought I can get away without re-parsing the entire document. Sorry for not showing the code near the floating window.

And I was experimenting in the debug window with expressions like this(and the one in the illustration above) when it didn't work in code:
`doc.attr("data-tl-id","ProductTileListView-0");`

This returns 387 (may vary based on changing content). That exact attribute exists ONLY in 1 div, I assumed it would just return those.

Is that expected behavior? Would be nice to know going forward.

Thanks again.

```
//s is the HTML for https://www.walmart.com/search/?query=031604016173
Document doc = Jsoup.parse(s);
Elements elements = doc.select("div").attr("data-tl-id","ProductTileListView-0");
System.out.println(elements.size());
```

**Comment by krystiangorecki** [comment] 2017-06-03 16:54
Your code:
```
doc.attr("data-tl-id","ProductTileListView-0");
```
is not doing what you think it does.
It has two parameters and it's a setter:
https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#attr-java.lang.String-java.lang.String-
It finds all elements with attribute "data-tl-id" regardless of its value and sets their values to "ProductTileListView-0". Then it returns all of them.

**Comment by jhy** [comment] 2017-06-08 15:13
Thanks for the investigation and detail on this! Closing.

**Closed by jhy** 2017-06-08 15:13 UTC
