### ISSUE TITLE
1.8.2 nextElementSibling() bug

### ISSUE THREAD

**Issue by smallufo** [jhy/jsoup#567] opened 2015-05-02 16:49 UTC
It has BUG !

```
  public static void main(String[] args) {
    String html =
      "<ul>" +
        "<li name=hello>hello</li>" +
        "<li>world</li>" +
        "<li>world</li>" +
      "</ul>";

    Document doc = Jsoup.parse(html);
    Element hello = doc.select("li[name]").first();
    System.out.println("hello = " + hello);

    Element nextSibling = hello.nextElementSibling();
    while(nextSibling != null) {
      System.out.println("nextSibling = " + nextSibling);
      nextSibling = nextSibling.nextElementSibling();
    }
  }
```

It will run into infinite loop. (1.8.2)

```
hello = <li name="hello">hello</li>
nextSibling = <li>world</li>
nextSibling = <li>world</li>
nextSibling = <li>world</li>
nextSibling = <li>world</li>
nextSibling = <li>world</li>
nextSibling = <li>world</li>
...
```

The code runs correctly in 1.7.x and 1.8.1 , but failed in 1.8.2

I think it is related to this commit : https://github.com/jhy/jsoup/commit/11f7c1bd7a2d12f0b1150aa246c61afefd11991f

**Comment by DenisGL** [comment] 2015-06-21 21:50
Yes, I do agree: I have the same issue with 1.8.2, and downgradding to 1.8.1 solved the issue. Thanks @smallufo .

**Comment by jhy** [comment] 2015-07-05 21:01
This is a dupe of #561, which is fixed on mainline

**Closed** 2015-07-05 21:01 UTC
