### ISSUE TITLE
".class" selector seems to be failing

### ISSUE THREAD

**Issue by edasaki** [jhy/jsoup#830] opened 2017-02-19 01:16 UTC
A more detailed post: http://stackoverflow.com/questions/42322374/jsoup-basic-class-css-selectors-not-working-html-shows-elements-exist-an

The problem can be summarized like so:

Debugging code:

    Elements as = doc.select("a");
    for (Element e : as) {
        if (e.classNames().size() > 0)
            M.debug(e.classNames());
        if(e.classNames().contains("bigChar")) {
            M.debug("found!");
        }
    }
    as = doc.select(".bigChar");
    M.debug("now: " + as);
    for (Element e : as) {
        if (e.classNames().size() > 0)
            M.debug(e.classNames());
    }

Output:

    [logo]
    [bigChar]
    found!
    [dotUnder]
    [dotUnder]
    [dotUnder]
    [dotUnder]
    [dotUnder]
    now: 

I've spent a while debugging this and I think the problem may have to do with malformed HTML. Attached is a sample input, and below is some simple code to run it (I am able to reproduce this problem consistently by reading from the file):

        try {
            Document doc = Jsoup.parse(new File("blahblah.txt"), "UTF-8");
            System.out.println(doc.html());
            System.out.println("FINAL");
            System.out.println(doc.select(".bigChar"));
            System.exit(0);
        } catch (IOException e) {
            e.printStackTrace();
        }

[blahblah.txt](https://github.com/jhy/jsoup/files/785471/blahblah.txt)

You can see in the HTML output that the "bigChar" class is used, but the .bigChar selector doesn't seem to find it.

In my run of the above code, my output is 

```
   </div> 
   <script type="text/javascript">
         $('#footer').css('top', $(document).height() - $('#containerRoot').height());
     </script>   
  </body>
 </html>
 FINAL
 

```

(i.e. nothing found for .bigChar)

**Comment by edasaki** [comment] 2017-02-19 01:23
Further debugging on the same blahblah.txt input:


            for (Element e : doc.getAllElements()) {
                if (e.hasClass("bigChar")) {
                    M.debug("Found iteratively");
                } else {
                    if (e.className().length() > 0)
                        M.debug(e.className());
                }
            }

Upon outputting all className()s in the Document, the bigChar is found in a className():
```
barTitle
barContent
arrow-general
bigChar
info
info
dotUnder
info
```

However, "Found iteratively" is never printed, so hasClass() is not finding it. 

Adding `e.className().contains("bigChar")` to the same if statement, like so, does find it.

                if (e.hasClass("bigChar") || e.className().contains("bigChar")) {

**Comment by edasaki** [comment] 2017-02-19 01:31
Further debugging:


                if (e.hasClass("bigChar") || e.className().contains("bigChar")) {
                    M.debug(e.attr("class").length());
                    M.debug("bigChar".length());
                    M.debug(e.hasClass("bigChar"));
                    M.debug(e.className().equalsIgnoreCase("bigChar"));
                    M.debug("Found iteratively");

Output:
```
7
7
false
true
Found iteratively
FINAL

```

Seems like something strange going on? Given that Element.hasClass() seems to first check by length.

**Comment by edasaki** [comment] 2017-02-19 01:50
After a lot more digging around, I found something strange - when I commented out my Jsoup 1.10.2 dependency, everything worked normally! I pulled up the dependency tree and realized that one of my other dependencies also has Jsoup as a dependency, but an older version:

[INFO] |  +- org.jsoup:jsoup:jar:1.9.2:compile

So it seems that the same issue does not occur on Jsoup 1.9.2.

I noticed that Element.hasClass() received a significant rewrite for "better performance" in this commit: https://github.com/jhy/jsoup/commit/d3c582598890d1e5e31e4f26e8452ad2dbf40b47

At the risk of incorrectly pointing fingers, perhaps the rewrite introduced some small bug? It is worth noting that the repo was at version 1.9.3 at the time of the commit, conveniently one patch after the version that works for me.

**Comment by cketti** [comment] 2017-02-19 03:51
This is already fixed in `master`. See #814.

Please also keep in mind that people who watch this repository are notified for every post you make. So it's better to first gather all the information you can, then create one post containing only the most relevant bits.

**Comment by edasaki** [comment] 2017-02-19 04:20
Oh sorry, my mistake. I haven't used GitHub enough to know about that but now that I know I will keep it in mind in the future!

However I believe this is a different issue than the one in the issue you linked. That fix was simply for case sensitivity, and the version that the bug appeared for me (1.10.2) on included that commit (I checked the source just to be sure).

**Comment by jhy** [comment] 2017-06-10 21:09
Thanks for the report and the sleuthing.

The problem is that the attribute *name* is now all lower case, and something's bugged in the case insensitivity of the attribute name.

You can see an e.g. here: http://try.jsoup.org/~l4ZA3QJ3p5WzWTD5y6v-tGu1Sh8 - change "Class" to "class" and it works. Will fix it up.

**Comment by jhy** [comment] 2017-06-10 21:25
Actually this is the same as #814 as @cketti pointed out :) I just forgot that try.jsoup wasn't on 1.10.3.

**Closed** 2017-06-10 21:30 UTC
Labels: duplicate
