### ISSUE TITLE
jsoup allows all tags to self-close, while browsers do not

### ISSUE THREAD

**Issue by michaelhkay** [jhy/jsoup#1876] opened 2023-01-02 13:14 UTC
JSoup appears to generate an incorrect DOM in response to the (erroneous) input

```
<body>
  <video autoplay="" id="remote" width="240"/>
  <script>
    ...
  </script>
</body>
```

(The "/" in the video tag should be ignored; it should be treated as a start tag to be closed later.)

Chrome and Firefox, validator.nu and AngleSharp all put the script element as a child of the video element. `JSoup` leaves `video` and `script` as siblings.

**Comment by jhy** [comment] 2023-01-05 04:07
Thanks - this is the same as #917 and #1037. See notes on the latter in particular. We will need to implement the idea on that to be able to resolve this, I believe. Unless there are other ideas?

**Comment by michaelhkay** [comment] 2023-01-05 09:50
Feel free to close as a duplicate. I quite agree that what JSoup is doing seems eminently reasonable in the circumstances, but we are more concerned with interoperability and conformance than with usability.

**Comment by jhy** [comment] 2023-01-05 09:53
I will leave it open as the closest #1037 is closed, and this description is clear.

**Comment by jhy** [comment] 2024-12-14 05:02
(On review, closing as dupe of #917. I am thinking of addressing this by renovating how we hold properties in Tags, and allow configuration of self-closing / void tags. And then moving the HTML default back into spec.)

**Closed by jhy** 2024-12-14 05:02 UTC
