### ISSUE TITLE
`<p> == false`, tag p is block

### ISSUE THREAD

**Issue by gMan1990** [jhy/jsoup#1430] opened 2020-09-25 16:15 UTC
https://github.com/jhy/jsoup/blob/89580cc3d25d0d89ac1f46b349e5cd315883dc79/src/main/java/org/jsoup/nodes/Element.java#L179
```java
    /**
     * Test if this element is a block-level element. (E.g. {@code <div> == true} or an inline element
     * {@code <p> == false}).
     * 
     * @return true if block, false if not (and thus inline)
     */
    public boolean isBlock() {
        return tag.isBlock();
    }
```
JavaDoc ERROR.

**Comment by jhy** [comment] 2020-12-11 05:31
Yup, dupe of #1342

**Closed by jhy** 2020-12-11 05:31 UTC
