### ISSUE TITLE
Elements in HashMaps Are Very Slow in 1.8.3

### ISSUE THREAD

**Issue by robliao** [jhy/jsoup#658] opened 2015-11-16 21:36 UTC
9813649 from #537 dramatically slows down HashMap that use elements as keys because now every hashcode call needs to do a child tree traversal. 

Sample callstack that indicates the slowdown.
```
at org.jsoup.nodes.TextNode.hashCode(TextNode.java:189)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.jsoup.nodes.Node.hashCode(Node.java:602)
	at org.jsoup.nodes.Element.hashCode(Element.java:1212)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:557)
```

**Comment by jhy** [comment] 2016-04-04 18:47
Treat this as a dupe of #688

**Closed by jhy** 2016-04-04 18:47 UTC
Labels: duplicate
