### ISSUE TITLE
JSoup produces invalid xml when html contains invalid comments

### ISSUE THREAD

**Issue by mvera** [jhy/jsoup#1941] opened 2023-04-19 21:21 UTC
If an html document contains invalid comment such this on  then the xml output is invalid.
java 17
Jsoup 1.15.4

Find below a minimalist junit test to reproduce.

package jsoup.test;

import static org.junit.Assert.fail;

import java.io.ByteArrayInputStream;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.jsoup.Jsoup;
import org.junit.Test;
import org.xml.sax.SAXException;

public class JsoupTest {
	@Test
	public void testHtml2XmlWithJsoupWithInvalidComment() {
		String htmlDoc = "<!DOCTYPE html><html><head></head><body></body></html>";
		try {
			html2xml(htmlDoc);
		} catch (Throwable t) {
			fail("bug has been fixed");
		}
	}

	private void html2xml(String htmlDoc) {
		try {
			// generate xml with jsoup
			org.jsoup.nodes.Document document = Jsoup.parse(htmlDoc);
			document.outputSettings().syntax(org.jsoup.nodes.Document.OutputSettings.Syntax.xml);
			document.outputSettings().charset("UTF-8");
			String xml = document.html();

			// parse xml with standard Java libraries
			DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
			DocumentBuilder builder = factory.newDocumentBuilder();
			ByteArrayInputStream input = new ByteArrayInputStream(xml.getBytes("UTF-8"));
			builder.parse(input);
		} catch (IOException | ParserConfigurationException | SAXException e) {
			throw new RuntimeException(e);
		}
	}
}

**Comment by jhy** [comment] 2023-04-24 01:40
Dupe of #1942

**Closed by jhy** 2023-04-24 01:40 UTC
